spring.application.name=cardapio

spring.datasource.url=jdbc:postgresql://localhost:5432/food
spring.datasource.username=nicolasludugerio
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect